service: ${env:SERVICE_NAME, 'Nest'}

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true

provider:
  name: aws
  stage: local
  runtime: nodejs18.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
